# Generated by Django 6.0.6 on 2026-06-16 10:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_name', models.CharField(default='player', max_length=50)),
                ('contact_number', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.PositiveIntegerField()),
                ('screenshot', models.FileField(upload_to='')),
                ('patron_id', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bcourt_app.patron')),
            ],
        ),
        migrations.CreateModel(
            name='schedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(default=datetime.datetime.now)),
                ('time_end', models.DateTimeField(default=datetime.datetime.now)),
                ('patron_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bcourt_app.patron')),
            ],
        ),
    ]
