# Generated by Django 6.0.6 on 2026-06-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcourt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patron_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='bcourt_app.patron'),
        ),
    ]
